[Emma_vertebrate_models]
git-tree-sha1 = "f601270881546e6feee22caf6ad7650e1776306e"

    [[Emma_vertebrate_models.download]]
    sha256 = "dea368acf22ba2cf79f7ce13c389264d8b5d73f635096ca2f77545154d88f4b4"
    url = "https://github.com/Pav-mis/Emma_vertebrate_models/archive/refs/tags/v1.1.tar.gz"
